CP-10044: use host attributes instead of pool attributes for network and storage
otherwise existing libvirt support for esx is not sufficient (no poolFactory will be
available) and xenrt will raise

> 'module' object has no attribute 'poolFactory'Traceback (most recent call last):
>   File "/usr/share/xenrt/venvs/878779/exec/xenrt/sequence.py", line 1938, in runThis
>     pool = xenrt.productLib(host=master).poolFactory(master.productVersion)(master)
> AttributeError: 'module' object has no attribute 'poolFactory'